### ISSUE TITLE
Make the Portfolio Responsive

### ISSUE THREAD

**Issue by akgupta0777** [akgupta0777/Portfolio-V2.0#1]
Make the portfolio responsive so that it can be perfectly viewed on other devices.
Current Status
Perfectly seen on PC and 15.6 inches Screens.

You can use anything but if you use **Media Queries** It will be great.

**Comment by chinmaym07** [comment]
Hey @akgupta0777 can I try this ..?

**Comment by akgupta0777** [comment]
Sure Go ahead.

**Comment by AyushMaji** [comment]
can I work on this project?

**Comment by akgupta0777** [comment]
Well I have already assigned it to @chinmaym07 
Let him give a try first. If he can't do this I will assign it to you.

**Comment by akgupta0777** [comment]
@AyushMaji  I respect your enthusiasm by the way.

**Comment by AyushMaji** [comment]
@akgupta0777  ok

**Comment by chinmaym07** [comment]
Hey @akgupta0777 I have opened a pr #2 .Please Reveiw.

**Comment by akgupta0777** [comment]
@chinmaym07 
Here is a medal for you 
🥇

**Comment by chinmaym07** [comment]
> @chinmaym07
> Here is a medal for you
> 1st_place_medal

Thankyou . :grinning:
