### ISSUE TITLE
Make the portfolio more mobile friendly.

### ISSUE THREAD

**Issue by akgupta0777** [akgupta0777/Portfolio-V2.0#6]
Currently, portfolio website looks like this on Mobile

![image](https://user-images.githubusercontent.com/51379307/135797816-225a4b37-4b61-4444-b0c3-934bac4989d8.png)

The person has to zoom the page in order to see the content. I want you to do something either in css or html in order to make the pages more user friendly.

**Comment by Himuu14** [comment]
just change in your code use size in "rem" compare to px .it will help as far as i know about css.

**Comment by akgupta0777** [comment]
@Himuu14 Do you wanna work on this and improve the site using your own suggestion. Wanna give a try ?

**Comment by Himuu14** [comment]
yes sure And after that I will copy your structure (html)  for making of mine portfolio

**Comment by akgupta0777** [comment]
Yeah sure that's why I open source mine portfolio.
